### ISSUE TITLE
Possible Python 3.8-incompatibility (multiple values for keyword argument 'size')

### ISSUE THREAD

**Issue by FrodeSolheim** [FrodeSolheim/fs-uae-arcade#18]
http://eab.abime.net/showthread.php?p=1369480#post1369480

    from_theme() got multiple values for keyword argument 'size'

**Comment by FrodeSolheim** [comment]
Looks like it was fixed for 3.0

**Comment by musuruan** [comment]
I still have this error on fs-uae-arcade v3.1.63 running on Fedora 35/x86_64. Python version is 3.10.1.

I see a lot of these in the log:
arcade.glui.texture.Texture.from_theme() got multiple values for keyword argument 'size'

**Comment by FrodeSolheim** [comment]
I checked once again, and it looks fine on the master branch. I tried running it as well - though I've only tested with Python 3.9.7. Can you run `fs-uae-arcade --version` and double-check the version?

**Comment by musuruan** [comment]
```
$ fs-uae-arcade --version
sys.path = ['/usr/share/fs-uae-arcade', '/usr/lib64/python310.zip', '/usr/lib64/python3.10', '/usr/lib64/python3.10/lib-dynload', '/usr/lib64/python3.10/site-packages', '/usr/lib/python3.10/site-packages']
3.1.63

$ python --version
Python 3.10.1

$ cat /etc/redhat-release 
Fedora release 35 (Thirty Five)

```

**Comment by FrodeSolheim** [comment]
How / where did you install fs-uae-arcade 3.1.63 from?

**Comment by FrodeSolheim** [comment]
I tested the version from the repo linked to from fs-uae.net. It seems to "work fine" on Fedora 35 (virtual machine). "Work fine" meaning I don't see the from_theme errors (It does not work properly in VirtualBox, but that seems to be due to use of an non-existing OpenGL function in the VMSVGA driver).

My theory is that somehow, fs-uae-arcade on your system picks up python files from an old arcade installation (?) Is there any stack trace associated with the errors in the log, which shows where the .py files are located?

**Comment by musuruan** [comment]
I am the RPM Fusion package maintainer for fs-uae, fs-uae-launcher and fs-uae-arcade. Yesterday I updated these packages to their latest versions. 

So, to answer your questions, I installed them from the sources you published here:
https://fs-uae.net/download#source

My system is clean. There were no previous installations of fs-uae related packages on this machine.

You can grab RPMs from RPM Fusion, or from koji if they are not yet in updates-testing:
https://koji.rpmfusion.org/koji/

Buildlogs are available here:
https://koji.rpmfusion.org/koji/buildinfo?buildID=21093

**Comment by Juppstein** [comment]
Interestingly I have this problem as well with python 3.10, the error message is exactly the same on my system (Ubuntu 22.04 LTS) using the latest packages provided via the repositories as described on the website.

https://paste.ubuntu.com/p/wTbnM5RVny/

**Comment by DoubleAgentDave** [comment]
I built this from source from the AUR on arch linux, it still displays this message. I've also tried it on a fresh build on a raspberry pi, and the error occurs there. The only common link between the two is the database files I'm using, I copied them across.

**Comment by barladur** [comment]
I am running  fs-uae-arcade version 3.1.63 on Kubuntu 24.04 with python3.12.

Looking at the source file "/usr/share/fs-uae-arcade/arcade/glui/texture.py", I notice the following fragments:

```
Lines 79-85:
            self.texture = self.from_theme(
                name,
                target=target,
                size=self.size,
                out_data=out_data,
                **kwargs
            )

...

Lines 223-229:
    @classmethod
    def from_theme(cls, name, size=None, **kwargs):
        if size is None:
            size = [0, 0]
        # im = resources.resource_qt_image(name)
        im = ArcadeTheme.get().qimage(name)
        return cls.load(im, size=size, **kwargs)

...

Lines 120-131:
    @classmethod
    def load(
        cls,
        im,
        mipmap=False,
        min_filter=None,
        wrap_s=gl.GL_CLAMP_TO_EDGE,
        wrap_t=gl.GL_CLAMP_TO_EDGE,
        target=gl.GL_TEXTURE_2D,
        size=None,
        out_data=None,
    ):
```

These method definitions and calls seem problematic, which can be seen more readily when reformatting the relevant lines:
``` 
self.from_theme( name, target=target, size=self.size, out_data=out_data, **kwargs )

def from_theme(cls, name, size=None, **kwargs):

cls.load(im, size=size, **kwargs)

def load( cls, im, mipmap=False, min_filter=None, wrap_s=gl.GL_CLAMP_TO_EDGE, wrap_t=gl.GL_CLAMP_TO_EDGE, target=gl.GL_TEXTURE_2D, size=None, out_data=None, ):
```

It seems that when method __from_theme__ is called, parameter __size__ receives the value of argument __target__, which is probably triggering the error message.

A similar problem seems to be occurring when __load__ is called, but I think it doesn't trigger error messages because execution doesn't reach this line.  

This is all I managed to find with this very light perusal of the source code. I hope this helps.
